KNOWLEDGE_BASE = [
    {
        "id": "KB-01",
        "title": "Password Reset",
        "content": "Employees can reset their own password via the self-service portal at any time. If locked out after 5 failed attempts, contact IT to unlock the account manually. No approval required."
    },
    {
        "id": "KB-02",
        "title": "VPN Access",
        "content": "VPN access is granted automatically to all full-time employees. Contractors require manager approval submitted via the access request form. VPN credentials expire every 90 days and must be renewed by the employee."
    },
    {
        "id": "KB-03",
        "title": "Laptop Replacement",
        "content": "Laptops are eligible for replacement after 3 years of service, or earlier in case of verified hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement."
    },
    {
        "id": "KB-04",
        "title": "Software Installation Requests",
        "content": "Standard software (listed in the approved catalog) can be self-installed. Non-catalog software requires IT Security review, which takes 3-5 business days."
    },
    {
        "id": "KB-05",
        "title": "Printer Troubleshooting",
        "content": "For printer issues, first check the printer queue and restart the print spooler. If the issue persists after restart, log a ticket with the printer's asset tag."
    },
    {
        "id": "KB-06",
        "title": "Email Mailbox Quota",
        "content": "Default mailbox quota is 25GB. Employees nearing quota should archive old mail. Quota increases beyond 25GB require manager approval and are capped at 50GB."
    },
    {
        "id": "KB-07",
        "title": "Guest Wi-Fi Access",
        "content": "Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. No IT ticket required."
    },
    {
        "id": "KB-08",
        "title": "Expense Software Access",
        "content": "Access to the expense management tool is granted by Finance, not IT. IT can only assist with login/technical issues once an account already exists."
    },
    {
        "id": "KB-09",
        "title": "Security Incident Reporting",
        "content": "Any suspected phishing email, malware, or unauthorized access attempt must be reported to security@veridian-corp.example immediately and should not be forwarded to other employees."
    },
    {
        "id": "KB-10",
        "title": "Work-From-Home Equipment",
        "content": "Employees working remotely more than 3 days/week are eligible for a one-time home office equipment allowance (chair, monitor). Requires manager sign-off and Finance processing — IT only handles the equipment shipping request once approved."
    },
    {
        "id": "Asset Management Policy",
        "title": "Hardware Refresh Cycle",
        "content": "All company-issued hardware, including laptops and monitors, follows a standard 4-year refresh cycle from date of issue. Early replacement outside this cycle requires Finance sign-off in addition to IT approval."
    }
]

TICKETS = [
    {"id": "TK-1042", "employee": "R. Verma", "issue_summary": "VPN credential expired", "status": "Resolved (closed)"},
    {"id": "TK-1043", "employee": "S. Iyer", "issue_summary": "Laptop replacement (3.2 yrs old)", "status": "Approved — pending fulfillment (active)"},
    {"id": "TK-1044", "employee": "A. Khan", "issue_summary": "Non-catalog software request", "status": "Pending Security review (active)"},
    {"id": "TK-1045", "employee": "P. Joshi", "issue_summary": "Mailbox quota increase", "status": "Approved at 35GB (closed)"},
    {"id": "TK-1046", "employee": "M. Das", "issue_summary": "Printer paper jam, floor 2", "status": "Resolved (closed)"},
    {"id": "TK-1047", "employee": "K. Singh", "issue_summary": "Home office equipment request", "status": "Pending Finance (active)"},
    {"id": "TK-1048", "employee": "T. Rao", "issue_summary": "Phishing email reported", "status": "Escalated to Security — under investigation (active)"},
    {"id": "TK-1049", "employee": "V. Nambiar", "issue_summary": "Password reset", "status": "Resolved (closed)"},
    {"id": "TK-1050", "employee": "J. Fernandes", "issue_summary": "Admin access request", "status": "Rejected — no business justification provided (closed)"},
    {"id": "TK-1051", "employee": "L. Menon", "issue_summary": "Guest Wi-Fi issued", "status": "Resolved (closed)"}
]

# Adding the 15 employee requests as test scenarios
REQUESTS = [
    {"id": "REQ-01", "employee": "Aditi Sharma", "email": "aditi.sharma@veridian-corp.example", "request": "My laptop won't turn on at all, it's completely dead, had it about 3.5 years now."},
    {"id": "REQ-02", "employee": "Vikram Chawla", "email": "vikram.chawla@veridian-corp.example", "request": "Can I get Wi-Fi access for a guest visiting our office tomorrow?"},
    {"id": "REQ-03", "employee": "Karan Mehta", "email": "karan.mehta@veridian-corp.example", "request": "I'm locked out of my account, tried my password 6 times."},
    {"id": "REQ-04", "employee": "Ritu Bhatia", "email": "ritu.bhatia@veridian-corp.example", "request": "Need approval to install a data-analysis tool that's not in the software catalog."},
    {"id": "REQ-05", "employee": "Sanjay Oberoi", "email": "sanjay.oberoi@veridian-corp.example", "request": "My VPN stopped working this morning, says credentials expired."},
    {"id": "REQ-06", "employee": "Meera Iyer", "email": "meera.iyer@veridian-corp.example", "request": "Printer on the 3rd floor keeps showing 'paper jam' even though there's no jam."},
    {"id": "REQ-07", "employee": "Farhan Ali", "email": "farhan.ali@veridian-corp.example", "request": "I've started working from home 4 days a week, how do I get a monitor?"},
    {"id": "REQ-08", "employee": "Ananya Reddy", "email": "ananya.reddy@veridian-corp.example", "request": "I think I got a phishing email asking for my login — forwarding it to a few teammates to check."},
    {"id": "REQ-09", "employee": "Rohit Desai", "email": "rohit.desai@veridian-corp.example", "request": "My mailbox is full and I can't send emails."},
    {"id": "REQ-10", "employee": "Kavya Pillai", "email": "kavya.pillai@veridian-corp.example", "request": "Can someone give me admin access to the finance reporting server? Need it urgently for month-end."},
    {"id": "REQ-11", "employee": "Nikhil Bansal", "email": "nikhil.bansal@veridian-corp.example", "request": "New contractor joining my team next week, they'll need VPN access."},
    {"id": "REQ-12", "employee": "Sneha Kulkarni", "email": "sneha.kulkarni@veridian-corp.example", "request": "I can't log into the expense tool, keeps saying invalid credentials."},
    {"id": "REQ-13", "employee": "Aman Gupta", "email": "aman.gupta@veridian-corp.example", "request": "Laptop screen is flickering on and off, had it 2 years, might just need a fix not a replacement."},
    {"id": "REQ-14", "employee": "Tanya Chopra", "email": "tanya.chopra@veridian-corp.example", "request": "Requesting approval to install a browser extension for productivity tracking."},
    {"id": "REQ-15", "employee": "Rahul Menon", "email": "rahul.menon@veridian-corp.example", "request": "hey can you help, its not working"}
]
